const data = {
    prdoducts:[
        {
            _id:'1',
            name: 'Captain',
            category: 'Monkey',
            image: '/images/product-1.png',
            price: 100000000,
            brand: 'OpenSea',
            rating: 4.5,
            numReviews: 10,
            description: 'new arivals',
        },
        {
            _id:'2',
            name: 'KOL',
            category: 'Monkey',
            image: '/images/product-2.png',
            price: 100000000,
            brand: 'OpenSea',
            rating: 4.5,
            numReviews: 10,
            description: 'new arivals',
        },
        {
            _id:'3',
            name: 'Monster',
            category: 'Monkey',
            image: '/images/product-3.png',
            price: 100000000,
            brand: 'OpenSea',
            rating: 4.5,
            numReviews: 10,
            description: 'new arivals',
        },
        {
            _id:'4',
            name: 'Natural M',
            category: 'Monkey',
            image: '/images/product-4.png',
            price: 100000000,
            brand: 'OpenSea',
            rating: 4.5,
            numReviews: 10,
            description: 'new arivals',
        },
        {
            _id:'5',
            name: 'Culi M',
            category: 'Monkey',
            image: '/images/product-5.png',
            price: 100000000,
            brand: 'OpenSea',
            rating: 4.5,
            numReviews: 10,
            description: 'new arivals',
        },
       
    ],
};
export default data;